
const {xmlToJson, buildNode, jsonToXml } = require("../index.js")
// --- Example Usage ---

async function runExample() {
    const exampleXml = `<?xml version="1.0" encoding="UTF-8"?>
<bookstore id="bs1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <!-- Main section for bestsellers -->
    <book id="b1" genre="fiction">
        <title>The Great Novel</title>
        <author>J. Doe</author>
        <price>19.99</price>
        <description>
            A story of
            mixed content.
        </description>
    </book>
    <book id="b2" genre="non-fiction">
        <title>The Science of XML</title>
        <author>A. Smith</author>
        <!-- This book is highly rated -->
        <price>29.50</price>
    </book>
    <comment>End of list.</comment>
</bookstore>`;

    console.log("--- Original XML ---");
    console.log(exampleXml);

    try {
        // 1. XML to JSON Conversion
        const json = xmlToJson(exampleXml);

        console.log("\n\n--- Converted JSON (Demonstrates Custom Structure) ---");
        // Print the JSON structure with indentation
        console.log(JSON.stringify(json, null, 4));

        // 2. JSON back to XML Conversion
        const xml = jsonToXml(json);

        console.log("\n\n--- Re-converted XML ---");
        console.log(xml);

    } catch (error) {
        console.error("\n\nAn error occurred during conversion. Custom parsers are less robust.", error.message);
    }
}

// Due to the lack of external libraries in this environment, you would need to 
// run this file in a Node.js environment to see the output.
// runExample();

// For demonstration in this environment, I will show the JSON output 
// of the conversion of the example XML:
/*
The JSON structure generated by the custom parser for the example XML is approximately:

{
    "bookstore": [
        {
            "@id": "bs1",
            "@xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
            "parts": [
                {
                    "#comment": "Main section for bestsellers"
                },
                {
                    "book": [
                        {
                            "@id": "b1",
                            "@genre": "fiction",
                            "parts": [
                                { "title": [{ "#text": "The Great Novel" }] },
                                { "author": [{ "#text": "J. Doe" }] },
                                { "price": [{ "#text": "19.99" }] },
                                { "description": [{ "#text": "A story of mixed content." }] }
                            ]
                        }
                    ]
                },
                {
                    "book": [
                        {
                            "@id": "b2",
                            "@genre": "non-fiction",
                            "parts": [
                                { "title": [{ "#text": "The Science of XML" }] },
                                { "author": [{ "#text": "A. Smith" }] },
                                { "#comment": "This book is highly rated" },
                                { "price": [{ "#text": "29.50" }] }
                            ]
                        }
                    ]
                },
                {
                    "comment": [{ "#text": "End of list." }]
                }
            ]
        }
    ]
}

*/
